services:
    app:
        container_name: wishlist-app
        image: ghcr.io/aintshefancy/wishlist
        ports:
            - 3280:3280
        volumes:
            - ./uploads:/usr/src/app/uploads
            - ./data:/usr/src/app/data
        env_file:
            - shinyenv.env
    tunnel:
        container_name: wishlist-proxy
        image: cloudflare/cloudflared:latest
        restart: unless-stop
        command: tunnel run
        environment:
            - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
    default:
        external:
            name: wishlist-app
