services:
    app:
        container_name: wishlist
        image: ghcr.io/aintshefancy/wishlist
        ports:
            - 3280:3280
        volumes:
            - ./uploads:/usr/src/app/uploads
            - ./data:/usr/src/app/data
        environment:
            ORIGIN: https://wishlist.shinydiscoballs.dev
            TOKEN_TIME: 72
