services:
    app:
        container_name: wonderful_borg
        image: ghcr.io/aintshefancy/wishlist
        ports:
            - 3280:3280
        volumes:
            - ./uploads:/usr/src/app/uploads
            - ./data:/usr/src/app/data
        env_file:
            - shinyenv.env
