services:
    app:
        container_name: wishlist-app
        image: ghcr.io/aintshefancy/wishlist
        ports:
            - 3280:3280
        volumes:
            - ./uploads:/usr/src/app/uploads
            - ./data:/usr/src/app/data
        env_file:
            - shinyenv.env
    cloudflared:
        container_name: wishlist-proxy
        image: docker.io/cloudflare/cloudflared:latest
        command: tunnel --no-autoupdate run --token
        environment: TUNNEL_TOKEN=${TUNNEL_TOKEN}
        depends_on:
            - app
